# Generated by Django 4.1.3 on 2024-01-31 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0002_rename_staff_content_photo_makeup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('progress', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('l_date', models.DateField()),
                ('price', models.CharField(max_length=20, null=True)),
                ('desc', models.CharField(max_length=20, null=True)),
                ('concre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolioApp.content')),
                ('makeup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolioApp.makeup')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolioApp.photo')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolioApp.customer')),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
