# Generated by Django 4.1.3 on 2024-02-01 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0003_portfolio_delete_products_delete_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
