# Generated by Django 4.1.3 on 2024-02-01 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0004_portfolio_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totamt', models.IntegerField()),
                ('conamt', models.IntegerField()),
                ('photoamt', models.IntegerField()),
                ('makeupamt', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolioApp.content')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolioApp.customer')),
                ('makeup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolioApp.makeup')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolioApp.photo')),
            ],
        ),
    ]
