# Generated by Django 4.1.3 on 2024-02-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0007_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_no',
            field=models.CharField(max_length=255),
        ),
    ]
