# Generated by Django 5.0.1 on 2024-02-21 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0008_alter_card_card_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='content_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_given', to='portfolioApp.content'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='makeup_artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_given', to='portfolioApp.makeup'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='photographer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_given', to='portfolioApp.photo'),
        ),
    ]
