# Generated by Django 5.0.1 on 2024-02-22 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0009_feedback_content_creator_feedback_makeup_artist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='content_creator',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='makeup_artist',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='photographer',
        ),
    ]
