# Generated by Django 5.0.1 on 2024-02-25 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0010_remove_feedback_content_creator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address',
            new_name='street',
        ),
    ]
