# Generated by Django 5.0.1 on 2024-02-25 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0011_rename_address_customer_street'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='street',
            new_name='Address',
        ),
    ]
