# Generated by Django 5.0.1 on 2024-02-25 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0012_rename_street_customer_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Address',
            new_name='address',
        ),
    ]
