# Generated by Django 5.0.1 on 2024-02-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0013_rename_address_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='houseno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='lname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='pin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
