# Generated by Django 5.0.1 on 2024-02-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0014_photo_district_photo_dob_photo_gender_photo_houseno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeup',
            name='district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='makeup',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='makeup',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='makeup',
            name='houseno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='makeup',
            name='lname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='makeup',
            name='pin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='makeup',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
