# Generated by Django 5.0.1 on 2024-02-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0015_makeup_district_makeup_dob_makeup_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='houseno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='lname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='pin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
