# Generated by Django 5.0.1 on 2024-02-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0016_content_district_content_dob_content_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='contact',
            field=models.CharField(default='9876566767', max_length=15),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='email',
            field=models.EmailField(default='null@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='p_title',
            field=models.CharField(default='student', max_length=50),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
