# Generated by Django 5.0.1 on 2024-02-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0019_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
