# Generated by Django 5.0.1 on 2024-03-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0020_customer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='pic',
            field=models.CharField(default='pic.png', max_length=200),
        ),
    ]
